tomcat:
  build: tomcat
  ports:
    - "8080:8080"
    - "8000:8000"
  links:
    - cassandra:cassandra
    - swift:swift
    - zookeeper:zookeeper
    - kafka:kafka
  volumes:
    - ./tomcat/webapps/:/usr/local/tomcat/webapps/
  environment:
    JAVA_OPTS: "-Xmx3064m -Xms3064m"
cassandra:
  build: cassandra
  ports:
    - "9042:9042"
    - "9160:9160"

swift:
  build: swift
  ports:
    - "8888:8888"
    - "5000:5000"
  volumes:
    - /srv

zookeeper:
  image: wurstmeister/zookeeper:3.4.6
  ports:
    - "2182:2181"

kafka:
  image: akrystian/kafka-docker
  links:
   - zookeeper:zookeeper
  environment:
    KAFKA_CREATE_TOPICS: "logging:1:1,indexing:1:1,ic_topology:1:1,xslt_topology:1:1"
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $$1}'"
  ports:
   - "9092:9092"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  restart: always

nimbus:
  build: storm
  command: storm nimbus
  hostname: nimbus
  links:
    - zookeeper:zookeeper
  ports:
    - "3773"
    - "3772"
    - "6627"
  restart: always

supervisor:
  build: supervisor
  command: storm supervisor
  hostname: supervisor
  ports:
    - "8000"
  links:
    - nimbus:nimbus
    - zookeeper:zookeeper
    - cassandra:cassandra
    - tomcat:tomcat
    - kafka:kafka
  restart: always

ui:
  build: storm
  command: storm ui
  ports:
    - "49080:8080"
  links:
    - nimbus:nimbus
    - zookeeper:zookeeper
  restart: always